### ISSUE TITLE
running the example gives: ### StateError: Bad state: Generated image width did not match original image width.

### ISSUE THREAD

**Issue by hansbak** [authpass/frameit-chrome#2]
if i run the example on Ubuntu linux I get the following result:

......
2021-05-13 13:14:04.019907 INFO process_screenshots - Processing images in Directory: 'metadata/android/en-US'
2021-05-13 13:14:04.026042 FINE process_screenshots - Rendering samsungapps-samsung-galaxy-s10-plus-appbar_menu with title: Example title 👍️ (SWEAT) and Frame{name: Samsung Galaxy S10, orientation: Orientation.portrait, offsetX: 41, offsetY: 71, width: 1440, image: File: '/home/dell/frameit-frames/latest/Samsung Galaxy S10 Prism Green.png'}
2021-05-13 13:14:05.631993 SEVERE frame - Error while creating frames.
### StateError: Bad state: Generated image width did not match original image width. Wrong device pixel ratio? was: 720 expected: 1440 ratio: 2.0
#0      FrameProcess._processScreenshot (package:frameit_chrome/src/frame_process.dart:235:9)
<asynchronous suspension>
#1      FrameProcess.processScreenshots (package:frameit_chrome/src/frame_process.dart:91:24)
<asynchronous suspension>
#2      runFrame (file:///home/dell/.pub-cache/hosted/pub.dartlang.org/frameit_chrome-1.0.0/bin/frameit_chrome.dart:125:5)
<asynchronous suspension>
#3      main (file:///home/dell/.pub-cache/hosted/pub.dartlang.org/frameit_chrome-1.0.0/bin/frameit_chrome.dart:61:5)
<asynchronous suspension>

any suggestions?

**Comment by hpoul** [comment]
Read the error message.. and then configure the pixel ratio..

**Comment by hpoul** [comment]
Check the --help of the command, it should be --pixel-ratio iirc

**Comment by hansbak** [comment]
Thanks for quick help, and the package itself. Could not make the help command to work, however looked in the source...

So the command line in the example needs to have the following parameter added: --pixel-ratio=1
